name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Tag-repo:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: tag git
      uses: dmyst3/tag-repo@main
      with:
        tag_name: 'v1.40.0'
        tag_message: 'test-tag'
   
